# Generated by Django 5.1.2 on 2024-10-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authormodel',
            name='book',
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.authormodel'),
        ),
    ]
