# Generated by Django 5.1.3 on 2024-11-10 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_photo_userconfirmationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='user_status',
            new_name='auth_status',
        ),
    ]
